### ISSUE TITLE
Request to Merge

### ISSUE THREAD

**Issue by FFX01** [npaul2811/hype#47]
Hey there. 

I'm the guyyou spoke to on Reddit about helping with your project. I've gone through and refactored the entire application. You can see what the merge would look like [here](https://github.com/npaul2811/hype/compare/master...FFX01:master). You can see that the merge is compatable.

Just a quick aside: You shouldn't ignore the migrations folder entirely as it is required for django in order to use the migrate shell command. You can ignore the migrations files directly though.

As far as changes go, you can see in the diff I posted above, there are quite a lot.

The application now works fairly well at serving up the model data as json. I wasn't sure if the idea was to build a django template based front end or if we wanted to go with something like react or angular. Or maybe we don't build a front end and allow end users to do that?

Either way, you can clone my fork, run migrations, go to the django admin and add a few posts and tags. Then go to /api/ and you can use DRFs front end to navigate through the api. That's the advantage of using the HyperLinkedModelSerializer. It's only 3 endpoints right now, but you can see that the data is being delivered properly.

Let me know what you think.

**Comment by npaul2811** [comment]
Whoa that's a lot of stuff to process. I'm at work right now and will have
to get back home and check out the PR. I'm pretty sure most of it won't
make sense to me, but I'm excited to learn all about it. Do join the Slack
so everyone can benefit from your insight man, thank you once again :)
